---
ID: "dfc29c70-501a-4b86-93d7-2abda834ebda"
Parent: "89f98c22-60b9-4251-b6b5-d28112f19ebb"
Template: "89f98c22-60b9-4251-b6b5-d28112f19ebb"
Path: /sitecore/templates/Feature/ACR/Promo/Promo/Promo Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {6B7D1C35-1929-4896-8EE3-932041808ADA}
    {89F98C22-60B9-4251-B6B5-D28112F19EBB}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240524T150141Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6b741ed6-b378-4fa7-a98a-9f178769f3c5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240524T150159Z
