---
ID: "9ae11160-aa23-424c-8c09-c9b66e166ab2"
Parent: "6b7d1c35-1929-4896-8ee3-932041808ada"
Template: "6b7d1c35-1929-4896-8ee3-932041808ada"
Path: /sitecore/templates/Feature/ACR/Promo/Promo/Promo/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240524T150052Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "71216885-caca-4c9c-ba51-7a094db10631"
      Hint: title
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1ed0dfa1-7bdc-45bb-8b15-4896eb08349e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240524T150057Z
