---
ID: "1da7c866-ed61-4af8-94ef-b49670561b40"
Parent: "f718bbac-63a4-4841-b30d-69d2f5380268"
Template: "f718bbac-63a4-4841-b30d-69d2f5380268"
Path: /sitecore/templates/Foundation/ACR/Rendering Parameters/Display License Link Parameter/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "03061771-0cb5-4484-b8c3-d363e56aa80f"
      Hint: DisplayLicenseLink
      Value: Left
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240526T064326Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\nbansal@acr.org
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nbansal@acr.org
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb17b9b6-126f-422c-a835-7e197a27f325"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nbansal@acr.org
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240527T113628Z
