---
ID: "8004fac3-2828-400e-a443-98e41022e853"
Parent: "776b866c-d744-481c-be6e-f22c3c76d385"
Template: "776b866c-d744-481c-be6e-f22c3c76d385"
Path: /sitecore/templates/Feature/ACR/Promo/Promo/Rendering Parameters/Promo Rendering Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240524T152921Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "298a318d-7456-4115-89ab-9a776123a826"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240524T152921Z
