---
ID: "f5a4887a-09bd-495d-92e3-669723b0cb8f"
Parent: "12f764d6-1364-47cd-a898-ec4898e47f54"
Template: "12f764d6-1364-47cd-a898-ec4898e47f54"
Path: /sitecore/templates/Foundation/ACR/Rendering Parameters/PageHeaderAlignment/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240526T064326Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\nbansal@acr.org
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nbansal@acr.org
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ad2a75d9-feb2-4bab-b940-7ceefea69c64"
    - ID: "b09acf55-21cd-4c5a-bac9-47f0184ca109"
      Hint: Alignment
      Value: Left
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nbansal@acr.org
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240526T064803Z
